slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    # Transform publishing
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters - Optimized for SRF08 sparse data
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_time_interval: 0.3  # Slower for sparse sensor data
    transform_timeout: 0.3
    
    # SRF08-specific correlation parameters
    # These are tuned for sparse, wide-beam ultrasonic sensors
    scan_buffer_size: 20  # Larger buffer for sparse data
    scan_buffer_maximum_scan_distance: 12.0
    link_match_minimum_response_fine: 0.03  # Very low for sparse sensors
    link_scan_maximum_distance: 3.0  # Allow larger scan matching distance
    
    # Loop closure - more tolerant for ultrasonic
    loop_search_maximum_distance: 5.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 6  # Lower for sparse data
    loop_match_maximum_variance_coarse: 5.0  # Higher tolerance
    loop_match_minimum_response_coarse: 0.15  # Lower threshold
    loop_match_minimum_response_fine: 0.25   # Lower threshold
    
    # Correlation search space - wider for ultrasonics
    correlation_search_space_dimension: 0.8  # Larger search space
    correlation_search_space_resolution: 0.02
    correlation_search_space_smear_deviation: 0.15
    
    # Coarse matching - more tolerant
    coarse_search_angle_offset: 0.524  # 30 degrees
    coarse_angle_resolution: 0.0524     # 3 degrees
    minimum_angle_penalty: 0.7
    minimum_distance_penalty: 0.3
    use_response_expansion: true