slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters - FIXED coordinate frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint                  # ✅ FIXED: Matches odometry plugin
    scan_topic: /scan
    mode: mapping

    # EMERGENCY: Conservative timing to prevent teleportation
    transform_publish_period: 0.1          # Slower publishing
    tf_buffer_duration: 5.0                # Shorter buffer
    transform_timeout: 1.0                 # Longer timeout
    minimum_time_interval: 0.5             # Process less frequently
    
    # EMERGENCY: Reduce processing load
    stack_size_to_use: 40000000           
    enable_interactive_mode: false        # Disable for stability
    debug_logging: true                   # Enable debugging
    
    # EMERGENCY: Very conservative scan matching
    use_scan_matching: true               # Keep enabled but conservative
    use_scan_barycenter: false
    minimum_travel_distance: 0.5          # Only process significant movements
    minimum_travel_heading: 0.8           # Large rotation threshold
    
    # EMERGENCY: Conservative scan processing
    scan_buffer_size: 5                   # Small buffer
    throttle_scans: 3                     # Skip many scans
    scan_buffer_maximum_scan_distance: 5.0
    map_update_interval: 5.0              # Slow map updates
    
    # EMERGENCY: Trust odometry heavily
    link_match_minimum_response_fine: 0.8  # Very high threshold
    link_scan_maximum_distance: 0.5       # Very short matching distance
    
    # EMERGENCY: Disable loop closure completely
    do_loop_closing: false
    
    # EMERGENCY: Minimal correlation search
    correlation_search_space_dimension: 0.1
    correlation_search_space_resolution: 0.1
    correlation_search_space_smear_deviation: 0.05
    
    # EMERGENCY: Trust odometry almost completely
    angle_variance_penalty: 0.01          # Almost no angle correction
    distance_variance_penalty: 0.01      # Almost no distance correction
    minimum_angle_penalty: 0.1
    minimum_distance_penalty: 0.1
    
    # EMERGENCY: Minimal angle search
    coarse_search_angle_offset: 0.01      # Tiny search
    fine_search_angle_offset: 0.001      # Minimal search
    coarse_angle_resolution: 0.1
    use_response_expansion: false